default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
        args: [ fix, feat, build, chore, ci, docs, style, refactor, perf, test, clean ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-pyproject]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
        args:
          - --fix
          - --config=pyproject.toml

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.971
  #   hooks:
  #     - id: mypy
  #       types: [python]
  #       args:
  #         - "--follow-imports=skip"
  #       additional_dependencies: ["django-stubs", "djangorestframework-stubs"]
