# Generated by Django 5.0.6 on 2024-05-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fare',
            old_name='available',
            new_name='available_seats',
        ),
    ]
